version: '3.5'

networks:
  contato_net:
    driver: bridge

services:
    # Postgres
    # 
    postgres:
        container_name: ${NOME_PROJETO}_postgres
        image: starefossen/pgrouting:10.1-2.4-2.5
        restart: always
        volumes:
          - "./dados/postgres_data:/var/lib/postgresql/data"
        environment:
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          - POSTGRES_DB=${POSTGRES_DB}
          - ALLOW_IP_RANGE=0.0.0.0/0
        ports:
          - "${POSTGRES_PORT}:5432"
        networks:
          - contato_net
    pgadmin4:
        container_name: ${NOME_PROJETO}_pgadmin4
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
            PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
        ports:
          - "${PGADMIN_PORT}:80"
        depends_on:
          - postgres
        networks:
          - contato_net
    python:
        container_name: ${NOME_PROJETO}_api
        image: "python:${PYTHON_VERSION}"
        command: bash -c "pip install -r /usr/src/app/requirements.txt && python /usr/src/app/run.py"        
        depends_on:
          - postgres
        volumes:
          - ".${DOCUMENT_ROOT}:/usr/src/app"
        ports:
          - "${PYTHON_PORT}:5000"
        environment:
          DATABASE_URL: postgres://contato@postgres/contato
        networks:
          - contato_net
